#!/bin/bash

#Cubiecopiadora realiza imagenes para memoria SD para cubieboard A10
#Copyright (C) 2017 Leon Ramos @fulvous
#
#Este archivo es parte de Cubiecopiadora
#
#Cubiecopiadora es software libre: Puede redistribuirlo y/o 
#modificarlo bajo los terminos de la Licencia de uso publico 
#general GNU de la Fundacion de software libre, ya sea la
#version 3 o superior de la licencia.
#
#Cubiecopiadora es distribuida con la esperanza de que sera util,
#pero sin ningun tipo de garantia; inclusive sin la garantia
#implicita de comercializacion o para un uso particular.
#Vea la licencia de uso publico general GNU para mas detalles.
#
#Deberia de recibir uan copia de la licencia de uso publico
#general junto con Cubiecopiadora, de lo contrario, vea
#<http://www.gnu.org/licenses/>.
#
#This file is part of Cubiecopiadora
#
#Cubiecopiadora is free software: you can redistribute it and/or 
#modify it under the terms of the GNU General Public License 
#as published by the Free Software Foundation, either version 3 
#of the License, or any later version.
#
#Cubiecopiadora is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Cubiecopiadora  If not, see 
#<http://www.gnu.org/licenses/>.

source herramientax/herramientax

#Evita que se ejecute el programa si hay errores
set -e

PWD_F="$(pwd)"

#Valores de ejecucion
VERBOSE=0
BORRAR=0
UBOOT_C=1
KERNEL_C=1
KERNEL_M=0
KERNEL_P=1
IMAGEN_C=1
DEBOOTSTRAP_C=1
DEBOOTSTRAP_G=0
LOG="${PWD_F}/cubiecopiadora.log"
SIZE_G="3"


#Locales
#LOCAL="es_MX.UTF-8"
#LOCALES="es_MX.UTF-8 UTF-8"
#LENGUAJE="es_MX:es"
LOCAL="C"
LOCALES="es_MX.UTF-8 UTF-8\nes_US.UTF-8 UTF-8"
LENGUAJE="en_US:en"
export LANG=$LOCAL
export LANGUAGE=$LENGUAJE
export LC_CTYPE=$LOCAL
export LC_TYPE=$LOCAL
export LC_NUMERIC=$LOCAL
export LC_TIME=$LOCAL
export LC_COLLATE=$LOCAL
export LC_MONETARY=$LOCAL
export LC_MESSAGES=$LOCAL
export LC_PAPER=$LOCAL
export LC_NAME=$LOCAL
export LC_ADDRESS=$LOCAL
export LC_TELEPHONE=$LOCAL
export LC_MEASUREMENT=$LOCAL
export LC_IDENTIFICATION=$LOCAL
export LC_ALL=$LOCAL

#Folders
KERNEL_F="linux-sunxi"
SUNXITOOLS_F="sunxi-tools"
UBOOT_F="u-boot-sunxi"
SALIDA_F="salida"
TMP_F="tmp"
DEBOOTSTRAP_F="sistemas"
FOLDERS="${KERNEL_F} ${UBOOT_F} ${SALIDA_F} ${TMP_F} ${DEBOOTSTRAP_F}"


#Valores para compilacion
TARJETA="Cubieboard"
CONFIG_TARJETA="sun4i_defconfig"
KERNEL_V="3.4"
UBOOT_V="sunxi"

#Valores para la imagen
DISTRO="xenial"
MNT="mnt"
IMAGEN="${TARJETA}-${KERNEL_V}-$(date +%Y%m%d).img"

DEBOOTSTRAP_I=${DISTRO}-db
DEBOOTSTRAP_EXT="tar.gz"
PAQUETES_DB="sudo,vim"

#Importando bibliotecas
source include/sys/salir.sh
source include/sys/uso.sh
source include/sys/dependencias.sh
source include/sys/borrar_temps.sh
source include/sys/descarga.sh
source include/sys/compila.sh
source include/sys/prepara_folders.sh
source include/sys/debootstrap.sh
source include/sys/crear_imagen.sh
source include/sys/formatear_particiones.sh
source include/sys/instalar_boot.sh
source include/sys/instalar_root.sh

#Checando si es superusuario
es_root

while getopts "gkmpurs:vh" OPT ; do
  case $OPT in
    g)
      DEBOOTSTRAP_G=1
      DEBOOTSTRAP_I=${DISTRO}-db-g
      ;;
    i)
      IMAGEN_C=0
      ;;
    k)
      KERNEL_C=0
      ;;
    m)
      KERNEL_M=1
      ;;
    p)
      KERNEL_P=0
      ;;
    u)
      UBOOT_C=0
      ;;
    s)
      SIZE_G=${OPTARG}
      if [ -z "${SIZE_G}" ] || [ ${SIZE_G} -eq 0 ] ; then
        res_err "Opcion invalida" "$OPTARG" "ERROR"
        uso
        exit 1
      fi
      ;;
    r)
      BORRAR=1
      ;;
    v)
      VERBOSE=1
      ;;
    h)
      uso
      exit 0
      ;;
    \?)
      res_err "Opcion invalida" "$OPTARG" "ERROR"
      uso
      exit 1
      ;;
  esac
done

case ${DISTRO} in
  wheezy)
    source include/sys/wheezy.sh
    ;;
  xenial)
    source include/sys/xenial.sh
    ;;
esac

debug "Tamaño de imagen: ${SIZE_G} GB"

#Checando configuraciones adicionales
if [ -f ${PWD_F}/include/configs.sh ] ; then
  informa "Cargando configuraciones" "${PWD_F}/include/configs.sh"
  source ${PWD_F}/include/configs.sh
  res_ok "Cargadas configuraciones" "${PWD_F}/include/configs.sh" "Exitoso"
fi

#Instalando paquetes necesarios
dependencias

#Borrar carpetas
borrar_temps

#Descarga fuentes
descarga

#Preparando folders temporales y de salida
prepara_folders

#Compilando
compila

### Continuando con el proceso de creacion de imagen
if [ "$IMAGEN_C" == "1" ] ; then
  informa "Generando imagen" "uSD" "${IMAGEN}"
  
  #Generando debootstrap
  debootstrap

  #Crear archivo de imagen y copiar u-boot
  crear_imagen

  #Montar particiones y formatearlas
  formatear_particiones

  #Instalando particion boot
  instalar_boot

  #Instalando particion root
  instalar_root

  #Instalando sources
  informa "Agregando" "sources.list"
  sources
  res_ok "Archivo" "Sources.list" "Exitoso"
  
  #Agregando entradas a fstab
  informa "Agregando" "/etc/fstab"
cat <<EOT >> ${PWD_F}/${TMP_F}/${MNT}/etc/fstab
none  /tmp  tmpfs defaults,noatime,mode=1777 0 0
/dev/mmcblk0p1 /boot vfat  defaults  0 0
EOT
  res_ok "Archivo cambiado" "/etc/fstab" "Exitoso"

  #Agregando archivo de interfaces
  informa "Agregando" "/etc/network/interfaces"
cat <<EOT > ${PWD_F}/${TMP_F}/${MNT}/etc/network/interfaces
auto lo
iface lo inet loopback
allow-hotplug eth0
iface eth0 inet dhcp
iface wlan0 inet dhcp
EOT
  res_ok "Archivo creado" "/etc/network/interfaces" "Exitoso"

  #Agregando archivo resolv.conf
  informa "Agregando" "/etc/resolv.conf"
cat <<EOT > ${PWD_F}/${TMP_F}/${MNT}/etc/resolv.conf
nameserver 8.8.8.8
nameserver 4.2.2.2
EOT
  res_ok "Archivo creado" "/etc/resolv.conf" "Exitoso"

  #Montando fs virtuales
  informa "Montando carpetas" "proc dev dev/pts sys"
  for i in proc dev sys; do
    mount -o bind /$i ${PWD_F}/${TMP_F}/${MNT}/$i
  done
  mount -o bind /dev/pts ${PWD_F}/${TMP_F}/${MNT}/dev/pts
  res_ok "Carpetas montadas" "proc dev dev/pts sys" "Exitoso"


  #Actualizar paquetes
  informa "Actualizando" "paquetes"
  debug "Creando tmp/update.sh"
cat <<EOT > ${PWD_F}/${TMP_F}/${MNT}/tmp/update.sh
#!/bin/bash
apt-get install -f -y
apt-get update -y
apt-get upgrade -y
EOT
  debug "Ejecutando tmp/update.sh"
  chroot ${PWD_F}/${TMP_F}/${MNT} \
    /usr/bin/qemu-arm-static /bin/bash \
    /tmp/update.sh
  debug "Borrando archivo de actualizacion"
  rm ${PWD_F}/${TMP_F}/${MNT}/tmp/update.sh
  res_ok "Actualizacion de" "sistema" "Exitoso"

  #Evitar actualizaciones automaticas
  informa "Evitar actualizaciones" "automaticas"
cat <<EOT > ${PWD_F}/${TMP_F}/${MNT}/etc/apt/apt.conf.d/71-no-recommends
APT::Install-Recommends "0";
APT::Install-Suggests "0";
EOT
  res_ok "Actualizaciones automaticas" "/etc/apt/apt.conf.d/71-no-recommends" "Exitoso"

  #Asegurarnos de tener terminal serial
  informa "Habilitar" "terminal serial"
  echo "T0:2345:respawn:/sbin/getty -L ttyS0 115200 vt100" >> ${PWD_F}/${TMP_F}/${MNT}/etc/inittab


  ##Colocando script de arranque
cat <<EOT > ${PWD_F}/${TMP_F}/${MNT}/etc/rc.local
##Coloca cualquier comando antes del exit 0
[ -f /usr/local/bin/inicial.sh ] && /usr/local/bin/inicial.sh
exit0
EOT

  [ ! -d ${PWD_F}/${TMP_F}/${MNT}/usr/local/bin ] && mkdir -p ${PWD_F}/${TMP_F}/${MNT}/usr/local/bin
  touch ${PWD_F}/${TMP_F}/${MNT}/usr/local/bin/primera
 
cat <<EOT > ${PWD_F}/${TMP_F}/${MNT}/usr/local/bin/inicial.sh
#!/bin/bash

if [ -f /usr/local/bin/primera ] ; then
        echo ",+" | sfdisk -N 2 /dev/mmcblk0 --force --no-reread
        rm /usr/local/bin/primera
        touch /usr/local/bin/segunda
        reboot
else 
        if [ -f /usr/local/bin/segunda ] ; then 
                rm /usr/local/bin/segunda
                resize2fs /dev/mmcblk0p2
        fi
fi

## rm /usr/local/bin/inicial.sh
EOT

  ##Dar permiso de ejecución a primer arranque
  chmod 755 ${PWD_F}/${TMP_F}/${MNT}/usr/local/bin/inicial.sh



  ##Procesos adicionales después de montado si es gráfico
  if [ "${DEBOOTSTRAP_G}" ==  "1" ] ; then

    case ${DISTRO} in
       "wheezy")
       
cat <<EOT > ${PWD_F}/${TMP_F}/${MNT}/usr/local/bin/inicial.sh
#!/bin/bash

if [ -f /usr/local/bin/primera ] ; then
        /usr/lib/arm-linux-gnueabihf/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > /usr/lib/arm-linux-gnueabihf/gdk-pixbuf-2.0/2.10.0/loaders.cache
        echo ",+" | sfdisk -N 2 /dev/mmcblk0 --force --no-reread
        rm /usr/local/bin/primera
        touch /usr/local/bin/segunda
        reboot
else 
        if [ -f /usr/local/bin/segunda ] ; then 
                rm /usr/local/bin/segunda
                resize2fs /dev/mmcblk0p2
        fi
fi

## rm /usr/local/bin/inicial.sh
EOT

        ##Dar permiso de ejecución a primer arranque
        chmod 755 ${PWD_F}/${TMP_F}/${MNT}/usr/local/bin/inicial.sh

        ;;
       "xenial")
       
cat <<EOT > ${PWD_F}/${TMP_F}/${MNT}/usr/local/bin/inicial.sh
#!/bin/bash

if [ -f /usr/local/bin/primera ] ; then
        echo ",+" | sfdisk -N 2 /dev/mmcblk0 --force --no-reread
        rm /usr/local/bin/primera
        touch /usr/local/bin/segunda
        reboot
else 
        if [ -f /usr/local/bin/segunda ] ; then 
                rm /usr/local/bin/segunda
                resize2fs /dev/mmcblk0p2
        fi
fi

## rm /usr/local/bin/inicial.sh
EOT

        ##Dar permiso de ejecución a primer arranque
        chmod 755 ${PWD_F}/${TMP_F}/${MNT}/usr/local/bin/inicial.sh

        ;;

    esac

  fi


  #Ejecutando los scripts custom-fuera
  informa "Ejecutando" "include/custom-fuera.sh"
  source ${PWD_F}/include/custom-fuera.sh


  #Ejecutando los scripts custom-chroot
  informa "Ejecutando" "include/custom-chroot.sh"
  debug "Copiando los scripts a la imagen"
  cp -v ${PWD_F}/herramientax/formato/colores.sh \
    ${PWD_F}/${TMP_F}/${MNT}
  cp -v ${PWD_F}/include/custom-chroot.sh \
    ${PWD_F}/${TMP_F}/${MNT}

  debug "Ejecutando el script en jaula"
  chroot ${PWD_F}/${TMP_F}/${MNT} \
    /usr/bin/qemu-arm-static /bin/bash \
    /custom-chroot.sh
  
  debug "Borrando los scripts de la imagen"
  rm ${PWD_F}/${TMP_F}/${MNT}/custom-chroot.sh
  rm ${PWD_F}/${TMP_F}/${MNT}/colores.sh
  
  res_ok "Script" "include/custom.sh" "Exitoso"
  
  informa "Desmontando" "sistemas de archivos"
  #Desmontando systemas de archivos
  sleep 3
  debug "Desmontando sistemas virtuales"
  umount ${PWD_F}/${TMP_F}/${MNT}/dev/pts
  for i in proc dev sys; do
    umount ${PWD_F}/${TMP_F}/${MNT}/$i
  done
  sleep 3
  umount /dev/mapper/${parts[1]}

  #Desmontando con kpartx
  debug "Desmontando particiones loop"
  kpartx -d ${PWD_F}/${TMP_F}/${IMAGEN}
  res_ok "Particion desmontada" "${PWD_F}/${TMP_F}/${IMAGEN}" "Exitoso"

  #Moviendo la imagen a la carpeta de salida
  if [ ! -d ${PWD_F}/${SALIDA_F} ] ; then
    informa "Creando la carpeta de salida" "${PWD_F}/${SALIDA_F}"
    mkdir -p ${PWD_F}/${SALIDA_F}
  fi
  informa "Moviendo imagen de folder temporal a" "salida" 
  mv -v ${PWD_F}/${TMP_F}/${IMAGEN}  \
    ${PWD_F}/${SALIDA_F}
  res_ok "Imagen ${IMAGEN} copiada a" "${PWD_F}/${SALIDA_F}" "Exitoso"

fi

