#!/bin/bash

#Cubiecopiadora realiza imagenes para memoria SD para cubieboard A10
#Copyright (C) 2017 Leon Ramos @fulvous
#
#Este archivo es parte de Cubiecopiadora
#
#Cubiecopiadora es software libre: Puede redistribuirlo y/o 
#modificarlo bajo los terminos de la Licencia de uso publico 
#general GNU de la Fundacion de software libre, ya sea la
#version 3 o superior de la licencia.
#
#Cubiecopiadora es distribuida con la esperanza de que sera util,
#pero sin ningun tipo de garantia; inclusive sin la garantia
#implicita de comercializacion o para un uso particular.
#Vea la licencia de uso publico general GNU para mas detalles.
#
#Deberia de recibir uan copia de la licencia de uso publico
#general junto con Cubiecopiadora, de lo contrario, vea
#<http://www.gnu.org/licenses/>.
#
#This file is part of Cubiecopiadora
#
#Cubiecopiadora is free software: you can redistribute it and/or 
#modify it under the terms of the GNU General Public License 
#as published by the Free Software Foundation, either version 3 
#of the License, or any later version.
#
#Cubiecopiadora is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Cubiecopiadora  If not, see 
#<http://www.gnu.org/licenses/>.

BORRAR="no"
VERBOSE=0
FOLDERS="herramientax linux-sunxi salida tmp"

function bienvenido {
cat <<EOT | fmt -

=================

Bienvenido a Cubiecopiadora

Este programa genera imagenes uSD para Cubieboard A10 con y sin cubiescreen.

Comenzaremos la instalacion de bibliotecas y codigo fuente.

leon.ramos<arroba>creadoresdigitales.com

==================

EOT
}

function uso {
  echo "$0 tiene las siguientes opciones:"
  cat <<EOT | fmt -
  
  -r     Borra todos los directorios
         permite descargar de nuevo

  -v     Muestra informacion adicional

  -h     Imprime esta ayuda

EOT

}


while getopts rvh OPT ; do
  case $OPT in
    r)
      BORRAR="si"
      ;;
    v)
      VERBOSE=1
      ;;
    h)
      uso
      exit 0
      ;;
    \?)
      echo "ERROR: Opcion invalida $OPTARG" >&2
      uso
      exit 1
      ;;
  esac
done

if [ "${BORRAR}" == "si" ] ; then
  [ $VERBOSE ] && echo "BORRANDO FUENTES"
  for folder in ${FOLDERS} ; do
    [ $VERBOSE ] && echo "Procesando $folder"
    [ -d $folder ] && rm -Rf $folder
  done
fi

[ $VERBOSE ] && echo "DESCARGANDO BIBLIOTECAS"
[ ! -d herramientax ] && git clone https://github.com/fulvous/herramientax.git

[ $VERBOSE ] && echo "ACTUALIZANDO BIBLIOTECAS"
if [ -d herramientax ] ; then
  cd herramientax
  git pull
  ./instala
  cd ..
fi

source herramientax/herramientax

jumbotron "Bibliotecas instaladas!" \
  "Ejecuta ${VERDE}copia${RESET} para hacer la nueva imagen." \
  "Se creara una imagen muy basica, es recomendable que modifiques ${CYAN}include/custom.sh${RESET} para agregar tu codigo y adecuar la imagen." \
  "Las imagenes resultantes estaran en el folder ${MAGENTA}salida${RESET}"

